### ISSUE TITLE
[Fonctionnalité] Daily avancé

### ISSUE THREAD

**Issue by L3mmy** [Tagueo/new-strad#1]
Mon idée serait d'améliorer le daily afin d'éviter le "spam" de Strad daily
Strad envoie un message à 11:59 et les membres réagissent avec l'émoji strad pour gagner leur blocks, ce même message serait supprimé le lendemain à 11:58 et la boucle se répète (Idée : Strad envoie un mp disant la somme du daily et signifiant quelle à bien été récupérée)
(Idée 2 : Strad poste son message dans #commands et le pin, il dit dans le salon #commands que le daily est disponible)

**Comment by Sinnoma** [comment]
Je sait pas je suis perplexe...

**Comment by SuperDelphi** [comment]
L'issue a été ouverte il y a longtemps, mais il n'est jamais trop tard pour y répondre.
Le salon #commandes du serveur a été créé dans le but d'y contenir les commandes réalisées par les membres. Cela permet aussi d'avoir une certaine trace des évènements.
Je ferme l'issue, n'hésitez tout de même pas à en lancer une autre si besoin est.
